body:
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: Please be specific
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Addon version & details
      description: "[Click here to see how to find the addon info](https://github.com/aclap-dev/video-downloadhelper/wiki/Where-can-I-find-my-versions%3F)"
      placeholder: Please paste here the Addon information
