body:
  - type: dropdown
    id: browser
    attributes:
      label: Which browser are you using?
      options:
        - Chrome
        - Mozilla Firefox
        - Microsoft Edge
        - Other
    validations:
      required: true
  - type: dropdown
    id: os 
    attributes:
      label: What is your Operating System?
      options:
        - Windows
        - MacOS
        - Linux
        - Other
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Your question
      placeholder: "Please be specific"
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Addon version & details
      description: "[Click here to see how to find the addon information](https://github.com/aclap-dev/video-downloadhelper/wiki/Where-can-I-find-my-versions%3F)"
      placehodler: Please paste here the Addon information
  # - type: markdown
  #   attributes:
  #     value: |
  #       ## Markdown header
  #       And some more markdown
  # - type: checkboxes
  #   attributes:
  #     label: Check that box!
  #     options:
  #       - label: This one!
  #         required: true
  #       - label: I won't stop you if you check this one, too
  # - type: markdown
  #   attributes:
  #     value: |
  #       ### The thrilling conclusion
  #       _to our template_
