body:
  - type: textarea
    id: question
    attributes:
      label: What's your issue?
      description: Do not paste your full license number!
    validations:
      required: true
  # - type: checkboxes
  #   id: checkboxes
  #   attributes:
  #     label: I confirm that I didn't not paste my full license number
  #     description: You may select more than one.
  #     options:
  #       - label: Yes
  #       - label: No
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
  # - type: input
  #   id: license
  #   attributes:
  #     label: The 10 first digit of your license numer or email address
