body:
  - type: markdown
    id: info
    attributes:
      value: |
        If you have lost your license, you should be able to recover it here : [Recover license](https://www.downloadhelper.net/recover-license). If you have a license or purchase issue, please do not share private information on our forums. Send us an email at _licenses@downloadhelper.net_. For other problems, please ask your question here:
  - type: textarea
    id: question
    attributes:
      label: What's your issue?
      description: Do not paste your full license number!
    validations:
      required: true
  - type: input
    id: license
    attributes:
      label: The 10 first digits (only 10) of your license number or email address
  - type: checkboxes
    attributes:
      label: I confirm that I did not not paste my full license number
      options:
        - label: I confirm
          required: true
